services:
  - type: web
    name: proyecto-horario
    runtime: docker
    plan: free
    port: 10000
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto-horario-db
          property: connectionString
      - key: CSP_SOLVER_URL
        value: http://localhost:8000
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: SENDGRID_API_KEY
        sync: false

databases:
  - name: proyecto-horario-db
    plan: free
    databaseName: db_horarios
    ipAllowList: []
